### ISSUE TITLE
update without migration tests

### ISSUE THREAD

**Issue by felixboehm** [owncloud-docker/base#1]
Missing argument to skip migration tests, here:
https://github.com/owncloud-docker/base/blob/master/rootfs/usr/local/bin/owncloud-migrate#L4

```
occ upgrade --no-interaction --skip-migration-tests
```

https://doc.owncloud.org/server/9.1/admin_manual/maintenance/upgrade.html#migration-test

**Comment by tboerger** [comment]
This have been dropped via https://github.com/owncloud-docker/base/commit/9b835c87c03c2ececca0453ec12581d14f1d6b33 because this flag doesn't exist on 10.0.0 anymore.

**Comment by tboerger** [comment]
Maybe I have to add a version switch the drops this flag only for owncloud versions >= 10.0.0?

**Comment by felixboehm** [comment]
Yes. Then it still works if someone using an older version. Makes sense
