### ISSUE TITLE
`OWNCLOUD_LOCKING_ENABLED` not documented

### ISSUE THREAD

**Issue by patrickjahns** [owncloud-docker/base#11]
While preparing different infrastructure setups - I realized that `OWNCLOUD_LOCKING_ENABLED` is not documented - and by default file locking will be disabled.

What is the reason for disabling it by default? 

cc @DeepDiver1975 @felixboehm @PVince81

**Comment by tboerger** [comment]
It's not documented by accident. Looks like it's also not defined within entrypoint.d, so it should be added there and being enabled by default.
