### ISSUE TITLE
No chown on mounted apps

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud-docker/base#126]
For a development case is can be pretty nasty that the container is chown the mounted apps.

I'm aware of the access issues we might face with owncloud/apache ...

maybe there is a solution somewhere ....

**Comment by tboerger** [comment]
The solution is to use bind mounts on your host for uid mapping, than you won't see any chown on your volume.

But that's totally up to the developer machine and nothing that should be changed within that image.

**Comment by DeepDiver1975** [comment]
Thx. Any quick pointer how to set this up in docker compose? Thx

**Comment by tboerger** [comment]
I think https://www.jujens.eu/posts/en/2017/Jul/02/docker-userns-remap/ could help you to get it right.
