### ISSUE TITLE
Cron doesn't pick up owncloud job

### ISSUE THREAD

**Issue by GrimDemon** [owncloud-docker/base#14]
I got fresh install of latest owncloud/server image with MariaDB and Redis running. Everything works fine except background jobs. Cron daemon is running in the container but ownCloud's cronjob isn't executing. What's wrong?

**Comment by GrimDemon** [comment]
Everything works fine when I deleted unnecessary spaces and set 15 standard minutes interval in /etc/cron.d/owncloud:
*/15 * * * * www-data /usr/bin/php -f /var/www/owncloud/cron.php

**Comment by tboerger** [comment]
It's not related to the spaces, we already discussed this internally and it looks like we need to touch the file at start time to get picked up by the cron daemon.

**Comment by GrimDemon** [comment]
Oh, OK. Maybe you could create that file as a last step of entrypoint scripts and it should be enough. I'm not a specialist of Docker, it's just a hint.

**Comment by tboerger** [comment]
Solved via https://github.com/owncloud-docker/base/pull/24

**Comment by Matthiasfranck** [comment]
Hi,

I am on owncloud 15.0 installed using the docker.

I have the following in `/etc/cron.d/owncloud`:

```
# cat /etc/cron.d/owncloud
*/1 * * * * www-data /usr/bin/cronjob
```

and looks like cron is also running:

```
# ps aux | grep cron
root       192  0.0  0.0   3828  2304 ?        Ss   Jan17   0:03 /usr/sbin/cron -l
root      2981  0.0  0.0   3308   652 pts/0    S+   15:18   0:00 grep cron
```
