### ISSUE TITLE
Add .well-known/openid-configuration rewrite rule

### ISSUE THREAD

**Issue by dschmidt** [owncloud-docker/base#175]
Hey,

last night I set up OIDC in my private ownCloud and working through the documentation I stumbled upon this:

https://doc.owncloud.com/server/next/admin_manual/configuration/user/oidc/oidc.html#prerequisites
https://doc.owncloud.com/server/next/admin_manual/configuration/user/oidc/oidc.html#set-up-service-discovery

TL;DR: I needed to setup a rewrite rule from `.well-known/openid-configuration` to `/apps/openidconnect/config`

I had to add this to my reverse proxy configuration. While being rather easy it was still kinda annoying to dig it up.
IMHO this is something the docker-image could provide out of the box. Having it enabled by default should be ok, as `/apps/openidconnect/config` is probably simply not found if openidconnect app is not enabled and that's exactly the same as `.well-known/openid-configuration` without the rewrite rule.

*Currently* I see no reason to opt-out of this behavior. The only reason I could imagine is another openidconnect app providing a different `.well-known` file ... but then again this could still be handled via the reverse proxy and would not be worse than today. So it's probably safe to always-enable this or make it opt-out.
Making it opt-in would of course be even more safe to not interfere with anything in existing setups, @xoxys suggested `OWNCLOUD_ENABLE_OIDC_REWRITE_URL`.

Please let me know what you think.
In chat @xoxys suggested it might belong into https://github.com/owncloud-docker/base/blob/master/latest/overlay/etc/templates/apache.conf

Thoughts?

**Comment by DeepDiver1975** [comment]
> Please let me know what you think.
> In chat @xoxys suggested it might belong into https://github.com/owncloud-docker/base/blob/master/latest/overlay/etc/templates/apache.conf

:+1:
