### ISSUE TITLE
Symlinks and installable apps Folder - best practice?

### ISSUE THREAD

**Issue by patrickjahns** [owncloud-docker/base#18]
Officially owncloud does not support symlinks (in the data folder) - I wonder how apps are affected:

We define our writable custom apps folder with `/var/www/owncloud/custom`
```
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/owncloud/custom',
      'url' => '/custom',
      'writable' => true,
    ),
  ),
```

Which actually is a symlink to `/mnt/data/apps/`

```
lrwxrwxrwx 1 root     root       14 Feb 15 12:05 custom -> /mnt/data/apps/
```

**Comment by tboerger** [comment]
If we don't symlink the folder from the web root custom styles or scripts are not resolvable. Since everything works totally fine like that I will close this issue again :)
