### ISSUE TITLE
Increase php timeouts

### ISSUE THREAD

**Issue by bitfag** [owncloud-docker/base#2]
According to https://doc.owncloud.org/server/10.0/admin_manual/configuration_files/big_file_upload_configuration.html

we need huge `max_input_time` and `max_execution_time` timeouts to upload big files. Currently these limits are not set thus big file uploads doesn't work.

**Comment by tboerger** [comment]
I will add environment variables for that ASAP.

**Comment by tboerger** [comment]
Solved via https://github.com/owncloud-docker/base/commit/f55203bd97946dc6a0dd1e774bb6cbe010dbe0b6
