### ISSUE TITLE
Include X-Request-ID header in apache logs 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud-docker/base#22]
By extending current `LogFormat` to include `\"%{X-Request-ID}i\"` - ref. http://httpd.apache.org/docs/current/mod/mod_log_config.html#formats

### `X-Request-ID` in ownCloud: 
- https://github.com/owncloud/core/pull/28144
- Client implementation: https://github.com/owncloud/client/issues/5853 and https://github.com/owncloud/client/pull/5897

**Comment by tboerger** [comment]
This is possible now, just add the environment variable `APACHE_LOG_FORMAT` with value `requestid ` and you will have the log format `%h %l %u %t "%r" %>s %O "%{Referer}i" "%{User-Agent}i" "%{X-Request-ID}i"`
