### ISSUE TITLE
New environment variable for customizing database port: OWNCLOUD_DB_PORT

### ISSUE THREAD

**Issue by armond1978** [owncloud-docker/base#266]
I have my MariaDB/MySQL database hosted on a non-default port but looking into `ENVIRONMENT.md` I can't find any environment variable to customize the default database port in my docker config. Something like `OWNCLOUD_DB_PORT`, just like what we already have for Redis (`OWNCLOUD_REDIS_PORT`) to customize the server port.

Can this be added in a future version?

**Comment by xoxys** [comment]
That's already possible using `OWNCLOUD_DB_HOST=dbhost:dbport`.

**Comment by xoxys** [comment]
If that's still not working for you, please let us know.
