### ISSUE TITLE
update after installing apps

### ISSUE THREAD

**Issue by voroyam** [owncloud-docker/base#3]
If you perform an update you need to run `occ upgrade` after enabling apps, like here:
https://github.com/owncloud-docker/base/blob/master/rootfs/etc/owncloud.d/35-apps.sh#L33

**Comment by tboerger** [comment]
Please tell more details, I didn't had this case so far.

**Comment by voroyam** [comment]
1. You install the owncloud app 9.1.4 in the UCS Appliance
2. You remove  owncloud app 9.1.4 in the UCS Appliance
3. You install the owncloud app 10.0.1 in the UCS Appliance

in 3. when enabling user_ldap_app the app is not up to date, and the ldap commands are not working

**Comment by tboerger** [comment]
Solved via https://github.com/owncloud-docker/base/commit/15e887dd8bff404cdd3003fe33143bea37b15fcb
