### ISSUE TITLE
Healthcheck file is not executable 

### ISSUE THREAD

**Issue by hmatthieu** [owncloud-docker/base#33]
Hello,

healthcheck failed all time with error : permission denied.

Resolved by : 
chmod +x /usr/bin/healthcheck
chmod +x /usr/local/bin/healthcheck

echo '#!/usr/bin/env bash
/usr/local/bin/healthcheck' > /usr/bin/healthcheck

Thanks for your work anyway ;)

**Comment by tboerger** [comment]
Solved via https://github.com/owncloud-docker/base/commit/88c23ae9203f782741f1fa2ca2e54aa004880605 and https://github.com/owncloud-docker/base/commit/1afd158863fb14af1f40c0412aa4c8edd47c5f16. Thanks for the report.
