### ISSUE TITLE
Errors:Could not open input file: /var/www/owncloud/occ

### ISSUE THREAD

**Issue by qinzheng** [owncloud-docker/base#34]
`volumes:
      - /home/mc2/owncloud-docker-server/volumes/web/data:/mnt/data
      - /home/mc2/owncloud-docker-server/volumes/web/owncloud:/var/www/owncloud`

**Comment by tboerger** [comment]
This only happens if `occ` is not present at `/var/www/owncloud`, what have you put into `/home/mc2/owncloud-docker-server/volumes/web/owncloud`?

**Comment by qinzheng** [comment]
there is nothing in `/home/mc2/owncloud-docker-server/volumes/web/owncloud`  I  want to mount  `/var/www/owncloud`  to my  host

**Comment by tboerger** [comment]
This doesn't work, you can only mount host volumes into containers and not the other way around. Download one of the official tarballs and place the content into that directory.
