### ISSUE TITLE
owncloud/base - won't run from MySQL

### ISSUE THREAD

**Issue by michal-jab** [owncloud-docker/base#343]
Hello,

I have a problem with OwnCloud/base that I cannot make this container work with MySQL. My database _is currently empty_ and I need _OwnCloud to build it_.

I currently have the version: **20.04** (https://hub.docker.com/layers/owncloud/base/20.04/images/sha256-2f82222dfa601a084d96c378fd654075b2ff609ba34191b6e558f68a388a0366)

**My parameters from the container in Environment:**
OWNCLOUD_TRUSTED_DOMAINS=localhost, 192.168.0.2, 192.168.0.99
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBIAN_FRONTEND=noninteractive
TERM=xterm
GOMPLATE_VERSION=v3.11.7
WAIT_FOR_VERSION=v2.0.2
RETRY_VERSION=v2.0.0
OWNCLOUD_DB_TYPE=mysql
OWNCLOUD_DB_NAME=OwnCloud
OWNCLOUD_DB_USERNAME=OwnCloud
OWNCLOUD_DB_PASSWORD=Passwords!
OWNCLOUD_DB_PREFIX=oc_
OWNCLOUD_DB_HOST=192.168.0.98:3306

**My container logs are:**
Actions
Creating volume folders...
Creating hook folders...
Waiting for MySQL...
services are ready!
Removing custom folder...
Linking custom folder...
Removing config folder...
Linking config folder...
Writing config file...
Fixing base perms...
Fixing data perms...
Fixing hook perms...
Upgrading server database...
Could not open input file: /var/www/owncloud/occ
Could not open input file: /var/www/owncloud/occ
Writing objectstore config...
Writing php config...
Updating htaccess config...
Could not open input file: /var/www/owncloud/occ
Creating volume folders...
Creating hook folders...
Waiting for MySQL...
services are ready!
Writing config file...
Fixing base perms...
Fixing data perms...
Fixing hook perms...
Upgrading server database...
Could not open input file: /var/www/owncloud/occ
Could not open input file: /var/www/owncloud/occ
Writing objectstore config...
Writing php config...
Updating htaccess config...
Could not open input file: /var/www/owncloud/occ

**I also checked whether the system in the container sees the MySQL server (192.168.0.98) and this is what the PING looks like:**
root@OwnCloud-base:/var/www/owncloud# ping 192.168.0.98
PING 192.168.0.98 (192.168.0.98): 56 data bytes
64 bytes from 192.168.0.98: icmp_seq=0 ttl=64 time=0.115 ms
64 bytes from 192.168.0.98: icmp_seq=1 ttl=64 time=0.092 ms
64 bytes from 192.168.0.98: icmp_seq=2 ttl=64 time=0.175 ms
64 bytes from 192.168.0.98: icmp_seq=3 ttl=64 time=0.114 ms
64 bytes from 192.168.0.98: icmp_seq=4 ttl=64 time=0.138 ms
64 bytes from 192.168.0.98: icmp_seq=5 ttl=64 time=0.105 ms
^C--- 192.168.0.98 ping statistics ---
6 packets transmitted, 6 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.092/0.123/0.175/0.027 ms

The container starts for a few seconds and then stops with status "Stopped for ____ with exit code 1".
**Can I ask for help in solving this problem?** I need MySQL because I have several OwnCloud clients on Windows and Android.

**Comment by xoxys** [comment]
Please take a look at the docs https://doc.owncloud.com/server/latest/admin_manual/installation/docker/#docker-compose

You have to use the `owncloud/server` image instead of the base image. Besides that, please use the forum https://central.owncloud.org/ for setup questions.
