### ISSUE TITLE
Image preview broken (Error 404) | Missing ENV overwrite option for preview_max_dimensions

### ISSUE THREAD

**Issue by DerFuz** [owncloud-docker/base#344]
### Describe the bug
Image Previews will not generate and load (error 404).
As previously described in [this issue](https://github.com/owncloud/core/issues/41238) on the core repository there is an issue with displaying image previews of larger images if some config-parameters are not set (correctly). I think this "problem" was introduced with [this commit](https://github.com/owncloud/core/commit/536f0b4003d20b589809a43b2dfc0378d982da38) because last year it worked for me without any problems in my installation.
Pictures larger than 6016x4000 seem to be affected and will not generate previews.

### Steps to reproduce
1. Run clean owncloud docker instance from [docker-compose file ](https://doc.owncloud.com/server/next/admin_manual/installation/docker/#docker-compose) without any additional environment variables
2. Upload different images in different sizes
3. Some will render a preview, some will fail

### Expected behaviour
All (Most) images render a preview

### Actual behaviour
![image](https://github.com/owncloud-docker/base/assets/11327876/6ece2bf7-0ab7-474f-8cf2-81b6bc6364d6)
#### Explanation of the screenshot
**left side** - clean unchanged fresh docker setup with some testpictures
**right side** - modified [/etc/templates/config.php](v20.04/overlay/etc/templates/config.php) after a fresh docker setup with some testpictures

portrait pictures: 3024x4032px
landscape pictures: 4032x3024px

On the unmodified installation previews are only generated for landscape pictures. (their resolution fits inside the default 6016x4000)

Sadly there are no helpful logs from inside the container (/mnt/data/files/owncloud.log is empty) that I could provide here...

Currently the option to set the [preview_max_dimensions](https://doc.owncloud.com/server/next/admin_manual/configuration/server/config_sample_php_parameters.html#define-the-maximum-dimensions-of-the-original-image-for-preview-generation) parameter as [environment-variable](ENVIRONMENT.md) for the container is not implemented.

### Possible solution
Modifications/Workaround to solve the problem:
1. add env  `OWNCLOUD_PREVIEW_MAX_DIMENSIONS=8000x8000` to docker-compose.yaml
2. run `docker-compose up -d`
  - env inside container: 
  ```
  root@2c74f10e1168:/var/www/owncloud# printenv | grep PREVIEW
  OWNCLOUD_PREVIEW_MAX_DIMENSIONS=8000x8000
  ```
3. adapt [/etc/templates/config.php](v20.04/overlay/etc/templates/config.php) because this will be used to generate the overwrite.config.php [when starting the container](v20.04/overlay/etc/owncloud.d/20-config.sh)
  - add following lines to the file: 
  ```
  if (getenv('OWNCLOUD_PREVIEW_MAX_DIMENSIONS') != '') {
    $config['preview_max_dimensions'] = getenv('OWNCLOUD_PREVIEW_MAX_DIMENSIONS');
  }
  ```
4. restart container (`docker stop owncloud_server`, `docker start owncloud_server`)
5. Enjoy previews (for images up to 8000x8000) ;)

### Server configuration
**ownCloud version:** 10.14.0.3 (fa429e56799220156d8a3a3dceb88f6dd0745718f1dbb04618b03131658ce01a)

**Updated from an older ownCloud or fresh install:** fresh install

*I hope my analysis is somewhat correct and can help identify and fix this effect*

**Comment by phil-davis** [comment]
Proposed enhancement to fix this: #345
