### ISSUE TITLE
Add the extra configuration to mysql to support 4-byte unicode

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud-docker/base#4]
See https://github.com/owncloud/documentation/issues/2924 for the details. This is needed since oC 10/X started supporting it on https://github.com/owncloud/core/issues/4513. 

An InvalidPath Sabre/DAV exception is raised when the config switch is not properly applied:

```
#0 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(1177): OCA\DAV\Connector\Sabre\Directory->getChild('\xF0\x9F\x92\x83')
#1 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/CorePlugin.php(590): Sabre\DAV\Server->createCollection('\xF0\x9F\x92\x83', Object(Sabre\DAV\MkCol))
#2 [internal function]: Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#3 /var/www/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#4 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:MKCOL', Array)
#5 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#6 /var/www/owncloud/apps/dav/appinfo/v1/webdav.php(63): Sabre\DAV\Server->exec()
#7 /var/www/owncloud/remote.php(165): require_once('/var/www/ownclo...')
#8 {main}
```

This applies to all images using this one as base.

**Comment by tboerger** [comment]
I'm not sure what you request to change. If you have switched an existing installation to mb4 you need to execute an occ command, otherwise it looks like you have to change nothing. So how is that related to the docker base image?

**Comment by SamuAlfageme** [comment]
I'm requesting the configuration described in https://github.com/owncloud/documentation/issues/2924 to be applied to our Docker base image so 4-byte unicode (emoji) support - an oC 10 feature - is included and working out of the box since the image uses MySQL as DB server. 

e.g. in our demo.owncloud.com instances, this is what happens:

![could_not_create](https://user-images.githubusercontent.com/2644445/28105255-01c35b24-66df-11e7-9bdc-a46d53381019.png)

> If you have switched an existing installation to mb4 you need to execute an occ command, otherwise it looks like you have to change nothing.

From the end user pov. I don't think switching the structure of the tables/running occ commands to have a fully working instance is really optimal.

**Comment by tboerger** [comment]
Solved via https://github.com/owncloud-docker/base/commit/642dcabcd3af2b6fbe0e203318394d3714bdf88d

**Comment by SamuAlfageme** [comment]
@tboerger neat; working as expected now 👍

**Comment by SamuAlfageme** [comment]
**Actually it's not working with the mariaDB basic setup** looks like I messed up with my DB settings and ended up testing on SQlite. @SergioBertolinSG will post more details on this.

**Comment by SergioBertolinSG** [comment]
I tried to use the variable OWNCLOUD_UTF8MB4_ENABLED=true

I have added it in the docker-compose of server image section:

https://github.com/owncloud-docker/server/blob/master/docker-compose.yml#L14-L23

It ended with an uninstalled server.

Didn't dig any further.

**Comment by tboerger** [comment]
Since this is the only option related to the ownCloud configuration it's up to you to launch MariaDB with the correct options.

**Comment by SamuAlfageme** [comment]
@tboerger shouldn't MariaDB "correct options" be included in our docker-compose setup; i.e. https://github.com/owncloud-docker/server/blob/4422f1f38bb1ed9c0c6c423f6cb0b7d356c3ff64/docker-compose.yml#L32-L48  ? 🤔

**Comment by tboerger** [comment]
Feel free to provide the required options.

**Comment by SamuAlfageme** [comment]
@tboerger they come in threes:

- MySQL conf. https://github.com/dockhippie/mariadb/pull/6 
- Migration for previous DBs: https://github.com/owncloud-docker/base/pull/9 
- Enabling support by default in docker-compose setup: https://github.com/owncloud-docker/server/pull/22

**Comment by SamuAlfageme** [comment]
@tboerger adapted the PRs to your concerns. Take a look, thx.
