### ISSUE TITLE
Issue with occ wrapper and whitespace

### ISSUE THREAD

**Issue by patrickjahns** [owncloud-docker/base#46]
When having commands containing a whitespace in the params, it is not correctly escaped 

Example: `occ ldap:set-config -vvv s02  ldapAgentName 'CN=SRV TEST OW,OU=Ser Accounts'`

Culprit https://github.com/owncloud-docker/base/blob/master/rootfs/usr/local/bin/occ#L5

**Comment by tboerger** [comment]
Solved via linked pull requests.
