### ISSUE TITLE
throw error when remove /var/www/owncloud/config

### ISSUE THREAD

**Issue by moonrailgun** [owncloud-docker/base#56]
docker logs below
```
Creating volume folders...
Creating hook folders...
Waiting for MySQL...
wait-for-it: waiting 180 seconds for db:3306
wait-for-it: db:3306 is available after 0 seconds
Removing config folder...
rm: cannot remove '/var/www/owncloud/config': Directory not empty
Creating volume folders...
Creating hook folders...
Waiting for MySQL...
wait-for-it: waiting 180 seconds for db:3306
wait-for-it: db:3306 is available after 0 seconds
Removing config folder...
rm: cannot remove '/var/www/owncloud/config': Directory not empty
```

https://github.com/owncloud-docker/base/blob/03ca7c5167b13ba0bd3069cd1e3ab50bca239658/rootfs/etc/owncloud.d/20-config.sh#L12-L19

just using standard [docker-compose](https://github.com/owncloud-docker/server/blob/master/docker-compose.yml) to start owncloud server

by the way. run docker image manually is also throw error

**Comment by tboerger** [comment]
And what is special on your setup that root can't remove a folder with rm -rf?

**Comment by moonrailgun** [comment]
i have no idea because i use root permission and use docker to ensure no other cause.
by the way. i use image docker.io/owncloud/server:10.0.8

**Comment by tboerger** [comment]
And what exactly are you doing? I can't reproduce this issue.

**Comment by moonrailgun** [comment]
i have no idea because i dont find others encounter this problem.
container is not run well so i also cant entry to check it .

maybe is my server's problem.....because i switch to other server. everything is ok

thank you any way:)

**Comment by tboerger** [comment]
Than I will close this issue. Thank you!

**Comment by tomasagray** [comment]
Experiencing this issue as well.

CentOS7  / 3.10.0-957.1.3.el7.x86_64

Running on secondary HDD, ext3

**Comment by lonkaut** [comment]
I experience this as well.  My special thing that I am doing is mounting config.php as a volume so that my config can persist.  

`
 volumes:
      - /datastore/ocnew:/mnt/data
      - ./config.php:/var/www/owncloud/config/config.php
`

Needing to do this because of "Logout button / reverse proxy / rewrite / CSRF / issue"

Advice?

**Comment by moonrailgun** [comment]
Seem that this case is not resolved until now. 

I just move to nextcloud. and every things is been ok.

**Comment by tboerger** [comment]
@lonkaut you don't need an additional volume for the config, it is already part of /mnt/data

@moonrailgun your issue seems to be related to your host system, three is nothing I can fix on our side since I can't reproduce the issue on our systems. Have fun with nextcloud.

**Comment by qmaxquique** [comment]
This is is related xfs filesystem with overlay mode.
https://github.com/docker/docker/issues/27358

**Comment by julianoBRL** [comment]
I have the same problem, I'm using centos7 and I'm using the commands to turn on the container:

```
docker volume create owncloud
docker run --name owncloud -v owncloud:/mnt/data -e OWNCLOUD_DOMAIN=<my ip>:9041 -p 9041:8080 owncloud/server
```
