### ISSUE TITLE
Skip "Fixing data perms..."

### ISSUE THREAD

**Issue by ThomDietrich** [owncloud-docker/base#6]
Hello :wave: 

The step to make sure permissions are set up correctly is a good idea but takes ages to complete once on a bigger data folder. How do you feel about allowing to skip it.

Also, I wonder if a simpler command would suffice:

```shell
chown -R www-data:www-data ${OWNCLOUD_VOLUME_ROOT}
```

**Comment by tboerger** [comment]
I'm not sure if it really makes sense to skip that as this command just ensures while start that the files are properly owned. The `chown -R www-data:www-data ${OWNCLOUD_VOLUME_ROOT}` is not an option, it's MUCH slower than the command we are using now, I have played around with all variations multiple hours.

**Comment by ThomDietrich** [comment]
Really? I didn't expect that.

Anyhow. For my data folder (2TB) the command takes around 20min, that's a bit too much if you are still playing around with the migration...

**Comment by tboerger** [comment]
Maybe we can give it a try to send this command into the background.

**Comment by ThomDietrich** [comment]
I'm not sure. If the files are indeed owned by another user, the step is important.

**Comment by tboerger** [comment]
But only the initial start should take long, after the initial chown it should be much faster.

**Comment by ThomDietrich** [comment]
Nope. The initial start did indeed correct all permissions, after that it doesn't change anything but still takes around 20 minutes.

**Comment by tboerger** [comment]
I have added an environment variable to disable chown. But you have to solve the permissions on your own! Solved via https://github.com/owncloud-docker/base/commit/3262d41d94101ae2742bb24056e2f25af792693f

**Comment by ThomDietrich** [comment]
Good tradeoff. thanks for acting on my concerns! 🍻
