### ISSUE TITLE
Allow using redis as session.save_handler

### ISSUE THREAD

**Issue by patrickjahns** [owncloud-docker/base#62]
Extend https://github.com/owncloud-docker/base/blob/master/rootfs/root/owncloud/php.ini to allow to set `session.save_handler` 

Introduce `PHP_SESSION_HANDLER` (defaults to `files`) and `PHP_SESSION_PATH` ( defaults to `${OWNCLOUD_VOLUME_SESSIONS}` )

**Comment by tboerger** [comment]
Solved via `OWNCLOUD_SESSION_SAVE_HANDLER` and `OWNCLOUD_SESSION_SAVE_PATH`.
