### ISSUE TITLE
Apache not listening on :80 or :443

### ISSUE THREAD

**Issue by mikenye** [owncloud-docker/base#67]
Hi All,

The latest owncloud/server:10.0 image appears to be broken.

Apache2 is not listening on ports 80 or 443.

I've been doing some troubleshooting into this, and it looks like this may be an issue with the base image. I'll post more when I've found more.

-Mike

**Comment by mikenye** [comment]
From within the image (installed net-tools):

`root@706400b3875b: /var/www/owncloud # netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN     
tcp        0      0 172.17.0.4:53758        172.17.0.2:3306         TIME_WAIT  
tcp        0      0 172.17.0.4:60450        172.17.0.3:6379         TIME_WAIT  
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path

root@706400b3875b: /var/www/owncloud # ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 /bin/sh /usr/sbin/apachectl -f /etc/apache2/apache2.c
   52 pts/0    Ss+    0:00 bash
  180 ?        Ss     0:00 /usr/sbin/cron -l
  185 ?        S      0:00 /usr/sbin/apache2 -f /etc/apache2/apache2.conf -DFORE
  186 ?        S      0:00 /usr/sbin/apache2 -f /etc/apache2/apache2.conf -DFORE
  187 ?        S      0:00 /usr/sbin/apache2 -f /etc/apache2/apache2.conf -DFORE
  188 ?        S      0:00 /usr/sbin/apache2 -f /etc/apache2/apache2.conf -DFORE
  189 ?        S      0:00 /usr/sbin/apache2 -f /etc/apache2/apache2.conf -DFORE
  190 ?        S      0:00 /usr/sbin/apache2 -f /etc/apache2/apache2.conf -DFORE
  580 pts/1    Ss     0:00 bash
  584 pts/1    R+     0:00 ps ax

`

**Comment by mikenye** [comment]
OK it looks like the behaviour of the container has changed? I used to map ports 80 & 443 through to the container, but it looks like port 8080 is now used?

I'll update my systems, apologies.

**Comment by tboerger** [comment]
Yeah sorry for this change, but it's required for the direction of root-less containers.

We started to write changelogs for our images, so in case of an update you can always check what changed beforehand.

**Comment by mikenye** [comment]
Its ok, I understand. :-)

In my configuration I have watchtower running to automatically update containers when a new version of their image is released, so this change caused three instances of OwnCloud to just stop responding.

I (probably somewhat nievely) didn't expect such a major change in the same version (running owncloud/server:10.0). Changing ports seems to be something you might do for a major release such as between 10 to 11.

Anyways, its all good my friend. Thanks for such a great container and application. Keep up the great work.

**Comment by tboerger** [comment]
Yeah we had a pretty long discussion about that topic, but in the end we had been at doing it. 

Great to hear that you like the container!
