### ISSUE TITLE
Missing php versions on docker / github

### ISSUE THREAD

**Issue by patrickjahns** [owncloud-docker/base#8]
Readme states 

>latest available as owncloud/base:latest at Docker Hub
7.1 available as owncloud/base:7.1 at Docker Hub
7.0 available as owncloud/base:7.0 at Docker Hub
5.6 available as owncloud/base:5.6 at Docker Hub
5.4 available as owncloud/base:5.4 at Docker Hub

Yet the branches are missing from github and no images with the according tags are available on DockerHub

**Comment by tboerger** [comment]
Right, need to drop it as it failed to build at all

**Comment by tboerger** [comment]
Dropped the references via 4894d6e2e8b1e031ca008f5c5337b1c113068723 for now.

**Comment by patrickjahns** [comment]
That's a pitty - been looking these days for "base-images" that i could extend with xdebug for development. 

Any other suggestions how to establish/provide docker containers for development?

**Comment by tboerger** [comment]
> Any other suggestions how to establish/provide docker containers for development?

Development and CI images will be pushed to https://github.com/owncloud-ci, I will cleanup this org to store only production and supported images.
