### ISSUE TITLE
Migrating a data for container

### ISSUE THREAD

**Issue by lmorales171290** [owncloud-docker/base#83]
I can not see my data from the host to the container, the version I had was 9 and I want to migrate to 10, as I do to be able to see the data folder in the container by grabbing the persistent volume from compose, besides being able to handle my data from the owncloud graphical interface

**Comment by tboerger** [comment]
I'm not sure I get your problem, the paths haven't been changed since the old container versions. Besides that I can't handle user support via the issue tracker, it's fine to report bugs, but for getting support please give https://central.owncloud.org a try.
