### ISSUE TITLE
Client IP forwarding not working on Owncloud behind Nginx 

### ISSUE THREAD

**Issue by lnx1288** [owncloud-docker/base#88]
I've setup my Owncloud container behind an Nginx reverse proxy. Everything works fine but the Owncloud server is not logging the remote client IP, it is logging the Nginx IP instead. My Nginx config is below. I was looking through the Owncloud variables and found OWNCLOUD_FORWARDED_FOR_HEADERS but don't know how to use it. After some reading I know that some configuration must be done in the web server side (i.e., the Owncloud) but as I don't know how to use the available variables for this purpose I'm a bit lost. Any ideas? Thanks in advance.

nginx.conf file:

`
server {
    listen 443 ssl;
    listen [::]:443ssl;

    add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        set_real_ip_from 192.168.1.0/24;
        real_ip_header X-Real-IP;
        real_ip_recursive on;
        proxy_pass http://owncloud:8080;
        include /config/nginx/proxy.conf;
    }
}
`

proxy.conf file:

`
/master/root/defaults/proxy.conf
client_body_buffer_size 128k;

proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;

proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 32 4k;
proxy_headers_hash_bucket_size 128;
proxy_headers_hash_max_size 1024;
`

**Comment by tboerger** [comment]
The container comes with the standard log format defined at https://github.com/owncloud-docker/php/blob/master/rootfs/etc/apache2/apache2.conf#L20, in any case of our deployments it never had to be changed. Looks like your reverse proxy isn't sending the proper headers to detect the right ip.

**Comment by lnx1288** [comment]
Seems like Nginx is sending these headers (got them from the Ownlcoud config report):
"HTTP Headers Information": {
            "HTTP Request": "GET \/apps\/configreport\/report HTTP\/1.1",
            "X-Forwarded-For": "REMOTE_CLIENT_IP",
            "X-Forwarded-Proto": "https",
            "X-Forwarded-Host": "MY_WEBSITE_DOMAIN:CUSTOM_PORT",
            "X-Forwarded-Ssl": "on",
            "Host": "owncloud:8080",

**Comment by lnx1288** [comment]
I partially solved the issue by changing the log format, adding the following to /etc/apache2/apache2.conf (inside the Onwlcoud container):

`LogFormat "%{X-Forwarded-For}i %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\ " combine`

Note: To restart the apache service I had to create the file `/etc/apache2/envvars` and define all the required Apache variables.

I assume that in order to change the log format in a permanent way I have to re-built the docker image right? Is there any other way?

**Comment by tboerger** [comment]
Is it possible that you are accessing the owncloud via ipv6 while it's showing the ip address of nginx in the access log? In that case it's a bug within docker which can be solved with a tool like https://github.com/robbertkl/docker-ipv6nat

**Comment by lnx1288** [comment]
I don't think so, the headers received by the Owncloud server (sent by Nginx) show the remote client IP (the ipv4 address) correctly in the X-Forwarded-For header. However, for some reason the remote_addr variable (again, this header is correctly sent by Nginx as the remote IP address of the client) is being set and logged by Owncloud as the Nginx IP

**Comment by tboerger** [comment]
Solved in recent base image, will be deployed to recent server images soon.
