### ISSUE TITLE
Configuring max_file_size and post_max_size in .htaccess

### ISSUE THREAD

**Issue by dchersey** [owncloud-docker/base#92]
I've been getting internal server errors syncing files larger than 512M through the desktop client, using the owncloud docker image. 

I tracked down the solution in the owncloud docs [here](https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/big_file_upload_configuration.html#configuring-your-webserver) 

which suggests I modify .htaccess to include
```
    php_value upload_max_filesize = 16G
    php_value post_max_size = 16G    
    php_value memory_limit 16G
```

I did this, and I used `docker cp` to copy the file into the running owncloud container. 
This solved my problem, BUT it's a separate step that will not survive a container rebuild. 

I looked at available environment variables and I don't see anything that would affect these values in either `php.ini` or `.htaccess`.

Is there a setting I am missing, or do I have to keep my work-around?

**Comment by tboerger** [comment]
At https://github.com/owncloud-docker/base/blob/master/rootfs/etc/templates/owncloud.ini#L5 we got env variables that set php.ini values, the default max upload size is already 20G, but you should never hit that with the desktop client because of chunked uploads.

**Comment by dchersey** [comment]
It is very strange to me then that updating these values directly in .htaccess resolved the errors I had been seeing.  If the default is 20G they should have had no effect. 

Here's the error I was getting on every file greater than 512MB; now they are all syncing successfully.
```
3,"time":"2019-05-29T23:57:07+00:00","remoteAddr":"72.69.225.243","user":"david","app":"PHP","method":"MOVE","url":"\/remote.php\/dav\/uploads\/david\/198844235\/.file","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 573294344 bytes) at \/var\/www\/owncloud\/lib\/composer\/guzzle\/stream\/Guzzle\/Stream\/Stream.php#71"}
```

**Comment by xoxys** [comment]
I think this problem no longer exists in the latest 10.8 release. If you still see this issue using the latest release, please open a new issue.
