### ISSUE TITLE
Cron runs every minute

### ISSUE THREAD

**Issue by cortho** [owncloud-docker/base#98]
Currently cron is configured to run every minute (see https://github.com/owncloud-docker/base/blob/master/rootfs/etc/cron.d/owncloud) which is not favorable on servers with multiple instances.

We are facing the same issue as e.g. https://github.com/owncloud/core/issues/30480#issuecomment-367607489 and would require a configurable cron value, so we would not have to patch the base code

**Comment by tboerger** [comment]
Maybe we can configure it optionally, the team states within that issue that it should be no issue to run it every minute, if there are jobs taking too long that should be reported.

**Comment by felixboehm** [comment]
What is the exact issue with that?

This is only triggering new jobs every minute, while recurring jobs have a builtin interval.
Calling it more often starts only new jobs and recurring jobs if the interval time is past.

So triggering once per minute provides timely follow ups for background jobs, not more load ...

**Comment by tboerger** [comment]
@cortho told me at the conference that they had a high load on machines running multiple containers and the load went down when they set the interval to every 15 minutes.

**Comment by cortho** [comment]
We are running 40-60 ownCloud dockers on the same server. With cron run every minute we reached the incredible load of ~20 whereas it fell back to less than 2 after we set the interval to 15 minutes.

**Comment by tboerger** [comment]
@felixboehm what do you prefer here? I would suggest to make the sync interval configurable by some environment variable.

**Comment by xoxys** [comment]
Sorry for the long-running issue. As a workaround, you can simply overwrite the default crontab file with a bind mount from the host. Besides that, we will add a config option as well.
