### ISSUE TITLE
Add mod_rpaf

### ISSUE THREAD

**Issue by cortho** [owncloud-docker/base#99]
In our setup with an nginx proxy we use `mod_rpaf` to retrieve actual IP addresses (see https://www.daveperrett.com/articles/2009/08/10/passing-ips-to-apache-with-nginx-proxy/)

ATM we're patching this into base, it would be useful to have this as a configurable option.

**Comment by felixboehm** [comment]
Would it be possible to install it on top of the server image, instead of patching base?

**Comment by tboerger** [comment]
I would like to reproduce that first, I'm pretty sure you can get the right ip into the logs without rpaf.

**Comment by tboerger** [comment]
The fix I have choosen is even easier, no need to install another package, just configure mod_remoteip and I'm getting the right remote IP if ownCloud is running behind an nginx-based reverse proxy. The PRs are linked above.

**Comment by cortho** [comment]
Excellent. Thank you very much.

**Comment by tboerger** [comment]
I need to apply some fixes to our Drone build pipeline, but this fix will be available soon, than you are only missing the env variable for cronjob scheduling.
